version: "3"
services:
  website:
    image: orchestronic.azurecr.io/orchestronic-app:website-latest
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=production
    command: ["npm", "run", "start"]
  socket-server:
    image: orchestronic.azurecr.io/orchestronic-app:socket-server-latest
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    command: ["node", "server.js"]
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
  redis:
    image: redis:7.2-bookworm
    expose:
      - 6379
  airflow-webserver:
    image: orchestronic.azurecr.io/orchestronic-app:airflow-webserver-latest
    command: webserver -p 8081
    ports:
      - "8081:8081"
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
      AIRFLOW__WEBSERVER__WEB_SERVER_PORT: "8081"
